language: python
sudo: false

env:
  - LUA="lua=5.3" FMT=""
  - LUA="lua=5.1" FMT="lcf"
  - LUA="lua=5.1" FMT="formatter"
  - LUA="lua=5.2" FMT=""
  - LUA="lua=5.3" FMT=""
  - LUA="lua=5.3" FMT="lcf"
  - LUA="luajit=2.1" FMT=""

cache:
    directories:
        - lua_install

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install --only-deps spec/test-scm-0.rockspec
  - luarocks install --only-deps lua-lsp-scm-1.rockspec
  - luarocks install $FMT || true

script:
  - luacheck -ur .
  - busted --verbose --coverage

after_success:
  - "luacov-coveralls --include '^%./lua%-lsp' --exclude '^%./lua%-lsp/lua%-parser'"

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: always
